services:
  database:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
  cache:
    image: memcached:1.6.7
    command:
      - '-m 1024'
      - '-c 1024'
      - '-t 2'
    ports:
      - "11211:11211"
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: always
    depends_on:
      - database
      - cache
    networks:
      - default
    ports:
      - "50051:50051"
